export const FETCH_NEWS_BUSINESS = "FETCH_NEWS_BUSINESS"
export const FETCH_BUSINESS_NEWS_SUCCESS = "FETCH_BUSINESS_NEWS_SUCCESS"
export const FETCH_BUSINESS_NEWS_FAILURE ="FETCH_BUSINESS_NEWS_FAILURE"